### ISSUE TITLE
Get a basic framework for missed event G

### ISSUE THREAD

**Issue by mdavezac** [DCPROGS/HJCFIT#3]
## TODO:
- [ ] Add exact recursion algorithm, #7.
- [ ] Add asymptotic algorithm, #8.
- [ ] Put the two together in interface similar to idealG. 

We probably want the two algorithms to be completely decoupled. However, we will want to do some caching. Maybe #7 and #8 should be implemented as template with set interface.
